name: booknewtable
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  assets: ^0.0.1
  cloud_firestore: ^5.0.2
  collection: ^1.18.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_map: ^7.0.2
  geolocator: ^12.0.0
  http: ^1.2.1
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/images/res1.jpg
  - lib/images/res3.jpg
  - lib/images/res2.jpg
  - lib/images/res4.jpg
  - lib/images/res5.jpg
  - lib/images/res6.jpg
  - lib/images/res7.jpg
  - lib/images/res8.jpg
  - lib/images/res9.jpg
  - lib/images/res10.jpg
  - lib/images/res11.jpg
  - lib/images/res12.jpg



