// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMJLPYR6V-LG5vMK-OsysZjDkO2aeAO0w',
    appId: '1:746383556678:web:7ed3684d1c2b2fb43eca47',
    messagingSenderId: '746383556678',
    projectId: 'book-new-table-aa2509',
    authDomain: 'book-new-table-aa2509.firebaseapp.com',
    storageBucket: 'book-new-table-aa2509.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr3RsxrQTxgdFWZ2lq7zFCCBI6sP8GVQA',
    appId: '1:746383556678:android:49856cf44dda08a73eca47',
    messagingSenderId: '746383556678',
    projectId: 'book-new-table-aa2509',
    storageBucket: 'book-new-table-aa2509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqxZqHNltFA50p1siTVF6JPqf_vsiWGfg',
    appId: '1:746383556678:ios:8fc73209f51dab623eca47',
    messagingSenderId: '746383556678',
    projectId: 'book-new-table-aa2509',
    storageBucket: 'book-new-table-aa2509.appspot.com',
    iosBundleId: 'com.example.booknewtable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqxZqHNltFA50p1siTVF6JPqf_vsiWGfg',
    appId: '1:746383556678:ios:8fc73209f51dab623eca47',
    messagingSenderId: '746383556678',
    projectId: 'book-new-table-aa2509',
    storageBucket: 'book-new-table-aa2509.appspot.com',
    iosBundleId: 'com.example.booknewtable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMJLPYR6V-LG5vMK-OsysZjDkO2aeAO0w',
    appId: '1:746383556678:web:1f0aa824c258bc933eca47',
    messagingSenderId: '746383556678',
    projectId: 'book-new-table-aa2509',
    authDomain: 'book-new-table-aa2509.firebaseapp.com',
    storageBucket: 'book-new-table-aa2509.appspot.com',
  );
}
